[package]
name = "rlox"
version = "0.1.0"
authors = ["Dhruv Patel <dhruv.nanosoft@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "9.0.0"
lazy_static = "1.4.0"
